### ISSUE TITLE
Refactor: Update to ES6

### ISSUE THREAD

**Issue by alexei-dayrit** [alexei-dayrit/trivial.io#16]
## ✅ Task List

> ##### Check list items that need to be done in order to complete the refactor.

- [x] Change all 'var' keywords into const and let
- [x] Change all functions to arrow functions
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
