### ISSUE TITLE
Refactor: use Fetch API instead XHR objects

### ISSUE THREAD

**Issue by alexei-dayrit** [alexei-dayrit/trivial.io#18]
## ✅ Task List

> ##### Check list items that need to be done in order to complete the refactor.

- [x] Change all XMLHttpRequests into promises using Fetch API
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
