### ISSUE TITLE
Bug: Game token isn't saved into local storage

### ISSUE THREAD

**Issue by alexei-dayrit** [alexei-dayrit/trivial.io#20]
#### Desired Behavior

> ##### The app should ...

The app should only fetch a game token if one doesn't exist in local storage.

#### Actual Behavior

> ##### The app does this instead ...

Currently the app doesn't save the session token into local storage and a new one is fetched every time a game starts.

#### Steps to Reproduce

> ##### To trigger the bug, you must ...

1. Start a game with any options
2. View local storage and see there's no sessionToken variable

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [x] Add sessionToken variable into data.js
- [x] Add conditional to only fetch for game token if one doesn't exist in local storage
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
