### ISSUE TITLE
Bug: reset game token

### ISSUE THREAD

**Issue by alexei-dayrit** [alexei-dayrit/trivial.io#22]
#### Desired Behavior

> ##### The app should ...

fetch for a new game token if the current one is expired.

#### Actual Behavior

> ##### The app does this instead ...

If local storage isn't cleared then app will reuse same token even if expired

#### Steps to Reproduce

> ##### To trigger the bug, you must ...

Wait 6 hours for the API token to expire and attempt to start a game

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [ ] Add conditional to fetch new token based on code returned from API
- **Clean Up**
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
